app/urls.py
from django.contrib import admin
from django.urls import path, include  # noqa: I101

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('Hypotenuse', views.triangle, name='triangle'),
    path('person', views.person, name='person'),
    path('person/<int:pk>', views.change_person, name='change_person'),
]

hw_10/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=30)
    suppliers = models.OneToOneField('Supplier', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'


class Client(models.Model):
    first_name = models.CharField(max_length=40)
    city = models.ForeignKey('City', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.first_name}'


class Towar(models.Model):
    product_name = models.CharField(max_length=40)
    clients = models.ManyToManyField('Client')

    def __str__(self):
        return f'{self.product_name}'


class Supplier(models.Model):
    products_name = models.CharField(max_length=40)

    def __str__(self):
        return f'{self.products_name}'

polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Person(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=40)

    def get_absolute_url(self):
        return reverse(args=[str(self.id)]) # noqa F821

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)


class ModelLog(models.Model):
    path = models.CharField(max_length=300)
    method = models.CharField(max_length=30)
    timestamp = models.TimeField(auto_now=True)

    def __str__(self):
        return self.path

polls/forms.py
from django import forms

from .models import Person


class Triangle(forms.Form):
    cathetus_1 = forms.DecimalField(label='Катет 1')
    cathetus_2 = forms.DecimalField(label='Катет 2')

    def clean_cathetus_1(self):
        cathetus_1 = self.cleaned_data.get('cathetus_1')
        if cathetus_1 < 0:
            raise forms.ValidationError('неправильоне значение')
        else:
            return cathetus_1

    def clean_cathetus_2(self):
        cathetus_2 = self.cleaned_data.get('cathetus_2')
        if cathetus_2 < 0:
            raise forms.ValidationError('неправильоне значение')
        else:
            return cathetus_2


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ["first_name", "last_name", "email"]

hw_10/views.py
from django.shortcuts import render  # noqa F401

# Create your views here.

polls/views.py
from math import sqrt

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect  # noqa I101
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .forms import PersonForm
from .forms import Triangle
from .models import Choice, Person, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def triangle(request):
    if request.method == 'POST':
        form = Triangle(request.POST)
        if form.is_valid():
            Hypotenuse = sqrt((form.cleaned_data['cathetus_1']) ** 2 + (form.cleaned_data['cathetus_2']) ** 2)
            return render(request, 'triangle.html', {
                'Hypotenuse': Hypotenuse,
            })
    else:
        form = Triangle()
    return render(request, 'triangle.html', {
        'form': form,
    })


def person(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)
        if form.is_valid():
            new_person = form.save()  # noqa F841
            return redirect("/polls")
    else:
        form = PersonForm()
    return render(request, 'person.html', {
        'form': form,
    })


def change_person(request, pk):
    new_person = get_object_or_404(Person, pk=pk)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=new_person)
        if form.is_valid():
            form.save()
            return redirect("/polls")
    else:
        form = PersonForm(instance=new_person)
    return render(request, 'person.html', {'form': form, })

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
    <p><a href="{% url 'polls:triangle' %}">Hypotenuse of a triangle</a></p>
    <p><a href="{% url 'polls:person' %}">Создать нового пользователя</a></p>
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

templates/person.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create person</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
</body>
</html>

templates/triangle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hypotenuse</title>
</head>
<body>
        {% if Hypotenuse %}
            <p> гипотенуза равна {{ Hypotenuse }} </p>
        {% else %}
            <form action="{% url 'polls:triangle' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit">
            </form>
        {% endif %}
</body>
</html>